apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sky4tress@gmail.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-route53-key
    solvers:
      - dns01:
          route53:
            accessKeyIDSecretRef:
              name: route53-credentials
              key: aws_access_key_id
            secretAccessKeySecretRef:
              name: route53-credentials
              key: aws_secret_access_key
            region: us-east-1  # Use your Route53 AWS region
