apiVersion: v1
kind: Namespace
metadata:
  name: skytunnel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skytunnel-deployment
  namespace: skytunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skytunnel-server
  template:
    metadata:
      labels:
        app: skytunnel-server
    spec:
      containers:
        - name: skytunnel-pod
          image: docker.io/skyfortress/skytunnel:latest
          env:
            - name: SSH_HOST_KEY
              valueFrom:
                secretKeyRef:
                  name: skytunnel-secrets
                  key: SSH_HOST_KEY
            - name: SSH_SERVER_PORT
              value: "22"
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 22
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: skytunnel-server
  namespace: skytunnel
spec:
  selector:
    app: skytunnel-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 22
      targetPort: 22
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skytunnel-server-ingress
  namespace: skytunnel
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-route53
spec:
  ingressClassName: nginx
  rules:
    - host: skytunnel.run
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skytunnel-server
                port:
                  number: 80
  tls:
    - hosts:
        - skytunnel.run
      secretName: letsencrypt-route53-key
