apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-clusterissuer-route53.yaml
  - deployment.yaml
namespace: skytunnel
images:
  - name: docker.io/skyfortress/skytunnel
    newTag: sha-53e2973
