apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-clusterissuer-route53.yaml
  - deployment.yaml

namespace: skytunnel
images:
  - name: docker.io/skyfortress/skytunnel
    digest: sha256:544f3aba456a792476ea5aa657edeb07cae0d11b