apiVersion: v1
kind: Namespace
metadata:
  name: kitebot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitebot-deployment
  namespace: kitebot
spec:
  replicas: 1
  strategy:
    type: Recreate  # Ensures the old pod is deleted before creating a new one
  selector:
    matchLabels:
      app: kitebot-server
  template:
    metadata:
      labels:
        app: kitebot-server
    spec:
      containers:
        - name: kitebot-server
          image: docker.io/skyfortress/kitebot:master
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kitebot-secrets
                  key: TELEGRAM_TOKEN
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kitebot-secrets
                  key: OPENAI_API_KEY
            - name: TELEGRAM_BOT_NAME
              value: "@noob_kite_bot"
