apiVersion: v1
kind: Namespace
metadata:
  name: kitebot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitebot-deployment
  namespace: kitebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitebot-server
  template:
    metadata:
      labels:
        app: kitebot-server
    spec:
      containers:
        - name: kitebot-server
          image: ghcr.io/skyfortress/kitebot:sha256-3e346acbf55d551d8c8f8e47780a37d5eec0fab739190ead86cdac262e7d68c1
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kitebot-secrets
                  key: TELEGRAM_TOKEN
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kitebot-secrets
                  key: OPENAI_API_KEY
            - name: TELEGRAM_BOT_NAME
              value: "@noob_kite_bot"
