apiVersion: v1
kind: Namespace
metadata:
  name: kitebot
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kitebot-pv
  labels:
    app: kitebot
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/kitebot/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitebot-pvc4
  namespace: kitebot
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: kitebot
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: kitebot
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        homelab: "true"
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        command:
        - "mongod"
        - "--bind_ip_all"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitebot-deployment
  namespace: kitebot
spec:
  replicas: 1
  strategy:
    type: Recreate  # Ensures the old pod is deleted before creating a new one
  selector:
    matchLabels:
      app: kitebot-server
  template:
    metadata:
      labels:
        app: kitebot-server
    spec:
      nodeSelector:
        homelab: "true"
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "unreliable"
          effect: "NoSchedule"
      containers:
        - name: kitebot-server
          image: docker.io/skyfortress/kitebot:latest
          envFrom:
            - secretRef:
                name: kitebot-secrets
          volumeMounts:
            - mountPath: /usr/src/web/images
              name: images-storage
      volumes:
        - name: images-storage
          persistentVolumeClaim:
            claimName: kitebot-pvc4
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: kitebot
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None  # Headless service for StatefulSet
