apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql18
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 18.x
    helm:
      values: |
        global:
          postgresql:
            auth:
              username: postgresql
              existingSecret: postgresql-credentials
              database: imggen
        primary:
          persistence:
            enabled: true
            size: 10Gi
          nodeSelector:
            homelab: "true"
        metrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: shared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
