apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skychat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/skyfortress/infra.git
    targetRevision: main
    path: skychat
  destination:
    server: https://kubernetes.default.svc
    namespace: skychat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
