apiVersion: v1
kind: Namespace
metadata:
  name: skychat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skychat-widget-deployment
  namespace: skychat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skychat-widget-server
  template:
    metadata:
      labels:
        app: skychat-widget-server
    spec:
      nodeSelector:
        master: "true"
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: skychat-widget-pod
          image: docker.io/skyfortress/skychat:widget
          env:
            - name: CORS_ALLOW_ORIGIN
              value: "*"
            - name: CORS_ALLOW_METHODS
              value: "GET,POST,OPTIONS,PUT,DELETE"
            - name: CORS_ALLOW_HEADERS
              value: "Content-Type,Authorization"
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: skychat-widget-server
  namespace: skychat
spec:
  selector:
    app: skychat-widget-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
