apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-api.yaml
  - deployment-widget.yaml
  - deployment-plugin.yaml
  - ingress.yaml
  - postgresql.yaml
  - qdrant.yaml
  - rabbitmq.yaml

configMapGenerator:
  - name: skychat-config
    namespace: skychat
    literals:
      - external_ip=38.242.216.132

replacements:
  - source:
      kind: ConfigMap
      name: skychat-config
      fieldPath: data.external_ip
    targets:
      - select:
          kind: Service
          name: skychat-widget-server
        fieldPaths:
          - spec.loadBalancerIP
      - select:
          kind: Service
          name: skychat-plugin-server
        fieldPaths:
          - spec.loadBalancerIP
