apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-api.yaml
  - deployment-widget.yaml
  - deployment-plugin.yaml
  - ingress.yaml
  - postgresql.yaml
  - qdrant.yaml
  - rabbitmq.yaml

configMapGenerator:
  - name: image-tags
    namespace: skychat
    literals:
      - api=api-sha-b2ded64
      - widget=widget-sha-d7a6a0c
      - plugin=plugin-sha-c5fb994

replacements:
  - source:
      kind: ConfigMap
      name: image-tags
      fieldPath: data.api
    targets:
      - select:
          kind: Deployment
          name: skychat-api-deployment
        fieldPaths:
          - spec.template.spec.containers.[name=skychat-api-pod].image
        options:
          delimiter: ":"
          index: 1
  - source:
      kind: ConfigMap
      name: image-tags
      fieldPath: data.widget
    targets:
      - select:
          kind: Deployment
          name: skychat-widget-deployment
        fieldPaths:
          - spec.template.spec.containers.[name=skychat-widget-pod].image
        options:
          delimiter: ":"
          index: 1
  - source:
      kind: ConfigMap
      name: image-tags
      fieldPath: data.plugin
    targets:
      - select:
          kind: Deployment
          name: skychat-plugin-deployment
        fieldPaths:
          - spec.template.spec.containers.[name=skychat-plugin-pod].image
        options:
          delimiter: ":"
          index: 1
