apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment-api.yaml
  - deployment-widget.yaml
  - deployment-plugin.yaml
  - ingress.yaml

configMapGenerator:
  - name: skychat-config
    namespace: skychat
    literals:
      - external_ip=38.242.216.132

vars:
  - name: EXTERNAL_IP
    objref:
      kind: ConfigMap
      name: skychat-config
      apiVersion: v1
    fieldref:
      fieldpath: data.external_ip
