apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 16.x
    helm:
      values: |
        global:
          postgresql:
            auth:
              username: skychat
              existingSecret: postgresql-credentials
              database: skychat
        primary:
          persistence:
            enabled: true
            size: 10Gi
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          nodeSelector:
            homelab: "true"
        metrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: skychat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
