apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
spec:
  project: default
  source:
    chart: qdrant
    repoURL: https://qdrant.github.io/qdrant-helm
    targetRevision: 0.7.2
    helm:
      values: |
        replicaCount: 1
        
        persistence:
          enabled: true
          size: 10Gi
        
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 1000m
        
        nodeSelector:
          master: "true"
        
        metrics:
          enabled: false
          serviceMonitor:
            enabled: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: skychat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
