apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    chart: rabbitmq
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 14.x
    helm:
      values: |
        auth:
          username: skychat
          existingPasswordSecret: rabbitmq-credentials
          existingErlangSecret: rabbitmq-credentials
        persistence:
          enabled: true
          size: 8Gi
        metrics:
          enabled: false
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
          limits:
            memory: 512Mi
            cpu: 1000m
        nodeSelector:
          master: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: skychat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
