apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    chart: rabbitmq
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 15.x
    helm:
      values: |
        persistence:
          enabled: true
          size: 8Gi
        metrics:
          enabled: false
        nodeSelector:
          master: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: skychat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
