apiVersion: v1
kind: Namespace
metadata:
  name: logic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-deployment
  namespace: logic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logic-server
  template:
    metadata:
      labels:
        app: logic-server
    spec:
      nodeSelector:
        master: "true"
      containers:
        - name: logic-pod
          image: docker.io/skyfortress/logic:latest
          ports:
            - containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: logic-server
  namespace: logic
spec:
  selector:
    app: logic-server
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logic-server-ingress
  namespace: logic
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-route53
spec:
  ingressClassName: nginx
  rules:
    - host: logic.skyfortress.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: logic-server
                port:
                  number: 3000
  tls:
    - hosts:
        - logic.skyfortress.dev
      secretName: letsencrypt-route53-key
